/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppStoresRouteImport } from './routes/_app.stores'
import { Route as AppChangesRouteImport } from './routes/_app.changes'
import { Route as AppUploadsSnapshotsRouteImport } from './routes/_app.uploads.snapshots'
import { Route as AppUploadsPromotionsRouteImport } from './routes/_app.uploads.promotions'
import { Route as AppUploadsProductsRouteImport } from './routes/_app.uploads.products'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppStoresRoute = AppStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => AppRoute,
} as any)
const AppChangesRoute = AppChangesRouteImport.update({
  id: '/changes',
  path: '/changes',
  getParentRoute: () => AppRoute,
} as any)
const AppUploadsSnapshotsRoute = AppUploadsSnapshotsRouteImport.update({
  id: '/uploads/snapshots',
  path: '/uploads/snapshots',
  getParentRoute: () => AppRoute,
} as any)
const AppUploadsPromotionsRoute = AppUploadsPromotionsRouteImport.update({
  id: '/uploads/promotions',
  path: '/uploads/promotions',
  getParentRoute: () => AppRoute,
} as any)
const AppUploadsProductsRoute = AppUploadsProductsRouteImport.update({
  id: '/uploads/products',
  path: '/uploads/products',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/changes': typeof AppChangesRoute
  '/stores': typeof AppStoresRoute
  '/uploads/products': typeof AppUploadsProductsRoute
  '/uploads/promotions': typeof AppUploadsPromotionsRoute
  '/uploads/snapshots': typeof AppUploadsSnapshotsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/changes': typeof AppChangesRoute
  '/stores': typeof AppStoresRoute
  '/': typeof AppIndexRoute
  '/uploads/products': typeof AppUploadsProductsRoute
  '/uploads/promotions': typeof AppUploadsPromotionsRoute
  '/uploads/snapshots': typeof AppUploadsSnapshotsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/changes': typeof AppChangesRoute
  '/_app/stores': typeof AppStoresRoute
  '/_app/': typeof AppIndexRoute
  '/_app/uploads/products': typeof AppUploadsProductsRoute
  '/_app/uploads/promotions': typeof AppUploadsPromotionsRoute
  '/_app/uploads/snapshots': typeof AppUploadsSnapshotsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/changes'
    | '/stores'
    | '/uploads/products'
    | '/uploads/promotions'
    | '/uploads/snapshots'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/changes'
    | '/stores'
    | '/'
    | '/uploads/products'
    | '/uploads/promotions'
    | '/uploads/snapshots'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/changes'
    | '/_app/stores'
    | '/_app/'
    | '/_app/uploads/products'
    | '/_app/uploads/promotions'
    | '/_app/uploads/snapshots'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stores': {
      id: '/_app/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof AppStoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/changes': {
      id: '/_app/changes'
      path: '/changes'
      fullPath: '/changes'
      preLoaderRoute: typeof AppChangesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/uploads/snapshots': {
      id: '/_app/uploads/snapshots'
      path: '/uploads/snapshots'
      fullPath: '/uploads/snapshots'
      preLoaderRoute: typeof AppUploadsSnapshotsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/uploads/promotions': {
      id: '/_app/uploads/promotions'
      path: '/uploads/promotions'
      fullPath: '/uploads/promotions'
      preLoaderRoute: typeof AppUploadsPromotionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/uploads/products': {
      id: '/_app/uploads/products'
      path: '/uploads/products'
      fullPath: '/uploads/products'
      preLoaderRoute: typeof AppUploadsProductsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChangesRoute: typeof AppChangesRoute
  AppStoresRoute: typeof AppStoresRoute
  AppIndexRoute: typeof AppIndexRoute
  AppUploadsProductsRoute: typeof AppUploadsProductsRoute
  AppUploadsPromotionsRoute: typeof AppUploadsPromotionsRoute
  AppUploadsSnapshotsRoute: typeof AppUploadsSnapshotsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChangesRoute: AppChangesRoute,
  AppStoresRoute: AppStoresRoute,
  AppIndexRoute: AppIndexRoute,
  AppUploadsProductsRoute: AppUploadsProductsRoute,
  AppUploadsPromotionsRoute: AppUploadsPromotionsRoute,
  AppUploadsSnapshotsRoute: AppUploadsSnapshotsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
