/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelectStoreRouteImport } from './routes/select-store'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShelvesIndexRouteImport } from './routes/shelves.index'
import { Route as PricesIndexRouteImport } from './routes/prices.index'
import { Route as PostersIndexRouteImport } from './routes/posters.index'
import { Route as ShelvesSceneRouteImport } from './routes/shelves.scene'
import { Route as PricesColdRouteImport } from './routes/prices.cold'
import { Route as ShelvesSceneSceneIndexRouteImport } from './routes/shelves.scene.$scene.index'
import { Route as ShelvesSceneSceneSetupRouteImport } from './routes/shelves.scene.$scene.setup'
import { Route as ShelvesSceneSceneRecordsRouteImport } from './routes/shelves.scene.$scene.records'
import { Route as ShelvesSceneSceneQaRouteImport } from './routes/shelves.scene.$scene.qa'
import { Route as ShelvesSceneSceneLastRouteImport } from './routes/shelves.scene.$scene.last'
import { Route as ShelvesSceneSceneInfoRouteImport } from './routes/shelves.scene.$scene.info'
import { Route as ShelvesSceneSceneFlowRouteImport } from './routes/shelves.scene.$scene.flow'

const SelectStoreRoute = SelectStoreRouteImport.update({
  id: '/select-store',
  path: '/select-store',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShelvesIndexRoute = ShelvesIndexRouteImport.update({
  id: '/shelves/',
  path: '/shelves/',
  getParentRoute: () => rootRouteImport,
} as any)
const PricesIndexRoute = PricesIndexRouteImport.update({
  id: '/prices/',
  path: '/prices/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostersIndexRoute = PostersIndexRouteImport.update({
  id: '/posters/',
  path: '/posters/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShelvesSceneRoute = ShelvesSceneRouteImport.update({
  id: '/shelves/scene',
  path: '/shelves/scene',
  getParentRoute: () => rootRouteImport,
} as any)
const PricesColdRoute = PricesColdRouteImport.update({
  id: '/prices/cold',
  path: '/prices/cold',
  getParentRoute: () => rootRouteImport,
} as any)
const ShelvesSceneSceneIndexRoute = ShelvesSceneSceneIndexRouteImport.update({
  id: '/$scene/',
  path: '/$scene/',
  getParentRoute: () => ShelvesSceneRoute,
} as any)
const ShelvesSceneSceneSetupRoute = ShelvesSceneSceneSetupRouteImport.update({
  id: '/$scene/setup',
  path: '/$scene/setup',
  getParentRoute: () => ShelvesSceneRoute,
} as any)
const ShelvesSceneSceneRecordsRoute =
  ShelvesSceneSceneRecordsRouteImport.update({
    id: '/$scene/records',
    path: '/$scene/records',
    getParentRoute: () => ShelvesSceneRoute,
  } as any)
const ShelvesSceneSceneQaRoute = ShelvesSceneSceneQaRouteImport.update({
  id: '/$scene/qa',
  path: '/$scene/qa',
  getParentRoute: () => ShelvesSceneRoute,
} as any)
const ShelvesSceneSceneLastRoute = ShelvesSceneSceneLastRouteImport.update({
  id: '/$scene/last',
  path: '/$scene/last',
  getParentRoute: () => ShelvesSceneRoute,
} as any)
const ShelvesSceneSceneInfoRoute = ShelvesSceneSceneInfoRouteImport.update({
  id: '/$scene/info',
  path: '/$scene/info',
  getParentRoute: () => ShelvesSceneRoute,
} as any)
const ShelvesSceneSceneFlowRoute = ShelvesSceneSceneFlowRouteImport.update({
  id: '/$scene/flow',
  path: '/$scene/flow',
  getParentRoute: () => ShelvesSceneRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/select-store': typeof SelectStoreRoute
  '/prices/cold': typeof PricesColdRoute
  '/shelves/scene': typeof ShelvesSceneRouteWithChildren
  '/posters/': typeof PostersIndexRoute
  '/prices/': typeof PricesIndexRoute
  '/shelves/': typeof ShelvesIndexRoute
  '/shelves/scene/$scene/flow': typeof ShelvesSceneSceneFlowRoute
  '/shelves/scene/$scene/info': typeof ShelvesSceneSceneInfoRoute
  '/shelves/scene/$scene/last': typeof ShelvesSceneSceneLastRoute
  '/shelves/scene/$scene/qa': typeof ShelvesSceneSceneQaRoute
  '/shelves/scene/$scene/records': typeof ShelvesSceneSceneRecordsRoute
  '/shelves/scene/$scene/setup': typeof ShelvesSceneSceneSetupRoute
  '/shelves/scene/$scene/': typeof ShelvesSceneSceneIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/select-store': typeof SelectStoreRoute
  '/prices/cold': typeof PricesColdRoute
  '/shelves/scene': typeof ShelvesSceneRouteWithChildren
  '/posters': typeof PostersIndexRoute
  '/prices': typeof PricesIndexRoute
  '/shelves': typeof ShelvesIndexRoute
  '/shelves/scene/$scene/flow': typeof ShelvesSceneSceneFlowRoute
  '/shelves/scene/$scene/info': typeof ShelvesSceneSceneInfoRoute
  '/shelves/scene/$scene/last': typeof ShelvesSceneSceneLastRoute
  '/shelves/scene/$scene/qa': typeof ShelvesSceneSceneQaRoute
  '/shelves/scene/$scene/records': typeof ShelvesSceneSceneRecordsRoute
  '/shelves/scene/$scene/setup': typeof ShelvesSceneSceneSetupRoute
  '/shelves/scene/$scene': typeof ShelvesSceneSceneIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/select-store': typeof SelectStoreRoute
  '/prices/cold': typeof PricesColdRoute
  '/shelves/scene': typeof ShelvesSceneRouteWithChildren
  '/posters/': typeof PostersIndexRoute
  '/prices/': typeof PricesIndexRoute
  '/shelves/': typeof ShelvesIndexRoute
  '/shelves/scene/$scene/flow': typeof ShelvesSceneSceneFlowRoute
  '/shelves/scene/$scene/info': typeof ShelvesSceneSceneInfoRoute
  '/shelves/scene/$scene/last': typeof ShelvesSceneSceneLastRoute
  '/shelves/scene/$scene/qa': typeof ShelvesSceneSceneQaRoute
  '/shelves/scene/$scene/records': typeof ShelvesSceneSceneRecordsRoute
  '/shelves/scene/$scene/setup': typeof ShelvesSceneSceneSetupRoute
  '/shelves/scene/$scene/': typeof ShelvesSceneSceneIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/select-store'
    | '/prices/cold'
    | '/shelves/scene'
    | '/posters/'
    | '/prices/'
    | '/shelves/'
    | '/shelves/scene/$scene/flow'
    | '/shelves/scene/$scene/info'
    | '/shelves/scene/$scene/last'
    | '/shelves/scene/$scene/qa'
    | '/shelves/scene/$scene/records'
    | '/shelves/scene/$scene/setup'
    | '/shelves/scene/$scene/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/select-store'
    | '/prices/cold'
    | '/shelves/scene'
    | '/posters'
    | '/prices'
    | '/shelves'
    | '/shelves/scene/$scene/flow'
    | '/shelves/scene/$scene/info'
    | '/shelves/scene/$scene/last'
    | '/shelves/scene/$scene/qa'
    | '/shelves/scene/$scene/records'
    | '/shelves/scene/$scene/setup'
    | '/shelves/scene/$scene'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/select-store'
    | '/prices/cold'
    | '/shelves/scene'
    | '/posters/'
    | '/prices/'
    | '/shelves/'
    | '/shelves/scene/$scene/flow'
    | '/shelves/scene/$scene/info'
    | '/shelves/scene/$scene/last'
    | '/shelves/scene/$scene/qa'
    | '/shelves/scene/$scene/records'
    | '/shelves/scene/$scene/setup'
    | '/shelves/scene/$scene/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SelectStoreRoute: typeof SelectStoreRoute
  PricesColdRoute: typeof PricesColdRoute
  ShelvesSceneRoute: typeof ShelvesSceneRouteWithChildren
  PostersIndexRoute: typeof PostersIndexRoute
  PricesIndexRoute: typeof PricesIndexRoute
  ShelvesIndexRoute: typeof ShelvesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/select-store': {
      id: '/select-store'
      path: '/select-store'
      fullPath: '/select-store'
      preLoaderRoute: typeof SelectStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shelves/': {
      id: '/shelves/'
      path: '/shelves'
      fullPath: '/shelves/'
      preLoaderRoute: typeof ShelvesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prices/': {
      id: '/prices/'
      path: '/prices'
      fullPath: '/prices/'
      preLoaderRoute: typeof PricesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posters/': {
      id: '/posters/'
      path: '/posters'
      fullPath: '/posters/'
      preLoaderRoute: typeof PostersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shelves/scene': {
      id: '/shelves/scene'
      path: '/shelves/scene'
      fullPath: '/shelves/scene'
      preLoaderRoute: typeof ShelvesSceneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prices/cold': {
      id: '/prices/cold'
      path: '/prices/cold'
      fullPath: '/prices/cold'
      preLoaderRoute: typeof PricesColdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shelves/scene/$scene/': {
      id: '/shelves/scene/$scene/'
      path: '/$scene'
      fullPath: '/shelves/scene/$scene/'
      preLoaderRoute: typeof ShelvesSceneSceneIndexRouteImport
      parentRoute: typeof ShelvesSceneRoute
    }
    '/shelves/scene/$scene/setup': {
      id: '/shelves/scene/$scene/setup'
      path: '/$scene/setup'
      fullPath: '/shelves/scene/$scene/setup'
      preLoaderRoute: typeof ShelvesSceneSceneSetupRouteImport
      parentRoute: typeof ShelvesSceneRoute
    }
    '/shelves/scene/$scene/records': {
      id: '/shelves/scene/$scene/records'
      path: '/$scene/records'
      fullPath: '/shelves/scene/$scene/records'
      preLoaderRoute: typeof ShelvesSceneSceneRecordsRouteImport
      parentRoute: typeof ShelvesSceneRoute
    }
    '/shelves/scene/$scene/qa': {
      id: '/shelves/scene/$scene/qa'
      path: '/$scene/qa'
      fullPath: '/shelves/scene/$scene/qa'
      preLoaderRoute: typeof ShelvesSceneSceneQaRouteImport
      parentRoute: typeof ShelvesSceneRoute
    }
    '/shelves/scene/$scene/last': {
      id: '/shelves/scene/$scene/last'
      path: '/$scene/last'
      fullPath: '/shelves/scene/$scene/last'
      preLoaderRoute: typeof ShelvesSceneSceneLastRouteImport
      parentRoute: typeof ShelvesSceneRoute
    }
    '/shelves/scene/$scene/info': {
      id: '/shelves/scene/$scene/info'
      path: '/$scene/info'
      fullPath: '/shelves/scene/$scene/info'
      preLoaderRoute: typeof ShelvesSceneSceneInfoRouteImport
      parentRoute: typeof ShelvesSceneRoute
    }
    '/shelves/scene/$scene/flow': {
      id: '/shelves/scene/$scene/flow'
      path: '/$scene/flow'
      fullPath: '/shelves/scene/$scene/flow'
      preLoaderRoute: typeof ShelvesSceneSceneFlowRouteImport
      parentRoute: typeof ShelvesSceneRoute
    }
  }
}

interface ShelvesSceneRouteChildren {
  ShelvesSceneSceneFlowRoute: typeof ShelvesSceneSceneFlowRoute
  ShelvesSceneSceneInfoRoute: typeof ShelvesSceneSceneInfoRoute
  ShelvesSceneSceneLastRoute: typeof ShelvesSceneSceneLastRoute
  ShelvesSceneSceneQaRoute: typeof ShelvesSceneSceneQaRoute
  ShelvesSceneSceneRecordsRoute: typeof ShelvesSceneSceneRecordsRoute
  ShelvesSceneSceneSetupRoute: typeof ShelvesSceneSceneSetupRoute
  ShelvesSceneSceneIndexRoute: typeof ShelvesSceneSceneIndexRoute
}

const ShelvesSceneRouteChildren: ShelvesSceneRouteChildren = {
  ShelvesSceneSceneFlowRoute: ShelvesSceneSceneFlowRoute,
  ShelvesSceneSceneInfoRoute: ShelvesSceneSceneInfoRoute,
  ShelvesSceneSceneLastRoute: ShelvesSceneSceneLastRoute,
  ShelvesSceneSceneQaRoute: ShelvesSceneSceneQaRoute,
  ShelvesSceneSceneRecordsRoute: ShelvesSceneSceneRecordsRoute,
  ShelvesSceneSceneSetupRoute: ShelvesSceneSceneSetupRoute,
  ShelvesSceneSceneIndexRoute: ShelvesSceneSceneIndexRoute,
}

const ShelvesSceneRouteWithChildren = ShelvesSceneRoute._addFileChildren(
  ShelvesSceneRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SelectStoreRoute: SelectStoreRoute,
  PricesColdRoute: PricesColdRoute,
  ShelvesSceneRoute: ShelvesSceneRouteWithChildren,
  PostersIndexRoute: PostersIndexRoute,
  PricesIndexRoute: PricesIndexRoute,
  ShelvesIndexRoute: ShelvesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
